#!/bin/bash

gnome-terminal -e roscore
gnome-terminal -e rosrun road_surface_recognition_2 making_environmental_pointcloud
gnome-terminal -e rosrun road_surface_recognition_2 publish_cloud_from_pcd
gnome-terminal -e  rosrun road_surface_recognition_2 tf_broadcaster_map_3dmap
gnome-terminal -e  rosrun road_surface_recognition_2 filtered_cloud_pub

sleep 5

gnome-terminal -e  rosservice call /up_map

